"use client";

import { labelClassName } from "./form-styles";

// The code is rendered server-side and arrives as markup, so it needs no
// client-side QR library. It sits on `bg-scan` rather than a surface token:
// a QR inverted by dark mode is a QR that scanners struggle with.
const downloadClassName =
  "rounded-full border border-line px-3 py-1.5 text-[.7rem] font-[850] tracking-[.06em] text-muted uppercase transition-colors duration-150 hover:border-pink hover:text-pink";

function download(href: string, filename: string) {
  const anchor = document.createElement("a");
  anchor.href = href;
  anchor.download = filename;
  anchor.click();
}

export default function QrCode({
  svg,
  png,
  link,
  slug,
  campaign,
}: {
  svg: string;
  png: string;
  link: string;
  slug: string;
  campaign: string | null;
}) {
  const filename = ["qr", slug, campaign].filter(Boolean).join("-");

  return (
    <div>
      <p className={labelClassName}>QR code</p>
      <div className="flex flex-col items-center gap-4 rounded-lg border border-line bg-surface-solid px-4 py-6">
        <div
          className="w-[200px] rounded-md bg-scan p-3 [&>svg]:block [&>svg]:h-auto [&>svg]:w-full"
          // Generated by the qrcode package in our own server action — the
          // only thing interpolated into it is a token we just minted.
          dangerouslySetInnerHTML={{ __html: svg }}
        />
        <div className="flex flex-wrap items-center justify-center gap-2">
          <button
            type="button"
            className={downloadClassName}
            onClick={() => {
              const url = URL.createObjectURL(
                new Blob([svg], { type: "image/svg+xml" })
              );
              download(url, `${filename}.svg`);
              URL.revokeObjectURL(url);
            }}
          >
            Download SVG
          </button>
          <button
            type="button"
            className={downloadClassName}
            onClick={() => download(png, `${filename}.png`)}
          >
            Download PNG
          </button>
        </div>
        <p className="text-center text-[.7rem] text-muted">
          SVG for print — it stays sharp at any size. Scans record{" "}
          <code className="font-mono">format: qr</code>, so they stay separate
          from clicks on the links above.
        </p>
        <code className="max-w-full font-mono text-[.65rem] break-all text-muted">
          {link}
        </code>
      </div>
    </div>
  );
}
